package com.asterfinancials.app

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.text.font.FontWeight
import kotlin.math.pow

private val Black=Color(0xFF050606); private val Panel=Color(0xFF0D0E0E); private val Gold=Color(0xFFD8AD37); private val WhiteGold=Color(0xFFF1D98A); private val Muted=Color(0xFF999990); private val Green=Color(0xFF18D779)
private enum class Tab(val label:String,val icon:ImageVector){HOME("Home",Icons.Default.Home),MARKETS("Markets",Icons.Default.ShowChart),AUTO("Auto Invest",Icons.Default.AutoGraph),CALC("Calculator",Icons.Default.Calculate),PROFILE("Profile",Icons.Default.Person)}

class MainActivity:ComponentActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);setContent{AsterApp()}}}

@Composable fun AsterApp(){var dark by remember{mutableStateOf(true)};var tab by remember{mutableStateOf(Tab.HOME)};MaterialTheme(colorScheme=if(dark)darkColorScheme(background=Black,surface=Panel,primary=Gold,onPrimary=Black)else lightColorScheme(primary=Color(0xFFA87518))){Column(Modifier.fillMaxSize()){Box(Modifier.weight(1f)){when(tab){Tab.HOME->Home{tab=it};Tab.MARKETS->Markets();Tab.AUTO->AutoInvest();Tab.CALC->Calculator();Tab.PROFILE->Profile{dark=!dark}}}};NavigationBar(containerColor=if(dark)Panel else Color.White){Tab.values().forEach{t->NavigationBarItem(selected=tab==t,onClick={tab=t},icon={Icon(t.icon,null,Modifier.size(19.dp))},label={Text(t.label,fontSize=8.sp)},colors=NavigationBarItemDefaults.colors(selectedIconColor=Gold,selectedTextColor=Gold,unselectedIconColor=Muted,unselectedTextColor=Muted))}}}}}

@Composable private fun Header(title:String,sub:String){Column(Modifier.padding(18.dp)){Text("ASTER",color=Gold,fontSize=11.sp,fontWeight=FontWeight.Bold,letterSpacing=2.sp);Text(title,fontSize=23.sp,fontWeight=FontWeight.Bold);Text(sub,color=Muted,fontSize=10.sp)}}
@Composable private fun CardBox(mod:Modifier=Modifier,content:@Composable ColumnScope.()->Unit){Card(mod,colors=CardDefaults.cardColors(Panel),content=content)}
@Composable private fun Home(go:(Tab)->Unit){LazyColumn(contentPadding=PaddingValues(bottom=20.dp)){item{Header("Financial command center","Premium automation & market intelligence")};item{CardBox(Modifier.padding(horizontal=16.dp)){Column(Modifier.padding(17.dp)){Text("AVAILABLE BALANCE",color=Muted,fontSize=9.sp);Text("— — —",fontSize=28.sp,fontWeight=FontWeight.Bold);Text("Verified balance appears after account connection.",color=Muted,fontSize=9.sp);Spacer(Modifier.height(12.dp));Button({go(Tab.PROFILE)},colors=ButtonDefaults.buttonColors(Gold)){Icon(Icons.Default.AccountBalanceWallet,null,Modifier.size(16.dp));Spacer(Modifier.width(6.dp));Text("Connect account",color=Black,fontSize=10.sp)}}};Spacer(Modifier.height(13.dp))};item{Text("QUICK ACCESS",color=Gold,fontSize=9.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(16.dp,5.dp));Row(Modifier.horizontalScroll(rememberScrollState()).padding(horizontal=16.dp),horizontalArrangement=Arrangement.spacedBy(8.dp)){Quick("Auto Invest",Icons.Default.AutoGraph){go(Tab.AUTO)};Quick("Markets",Icons.Default.ShowChart){go(Tab.MARKETS)};Quick("Calculator",Icons.Default.Calculate){go(Tab.CALC)}};Spacer(Modifier.height(14.dp))};item{CardBox(Modifier.padding(horizontal=16.dp)){Column(Modifier.padding(16.dp)){Text("Trade. Stake. Earn. Repeat.",fontSize=17.sp,fontWeight=FontWeight.Bold);Text("A premium command center for automated strategies and live market intelligence.",color=Muted,fontSize=10.sp,modifier=Modifier.padding(top=5.dp));Text("No invented account balances or transactions.",color=Gold,fontSize=9.sp,modifier=Modifier.padding(top=8.dp))}}}}}
@Composable private fun Quick(t:String,i:ImageVector,go:()->Unit){Column(Modifier.width(105.dp).background(Panel).clickable{go()}.padding(12.dp),horizontalAlignment=Alignment.CenterHorizontally){Icon(i,null,tint=Gold,modifier=Modifier.size(21.dp));Text(t,fontSize=9.sp,modifier=Modifier.padding(top=5.dp))}}
@Composable private fun AutoInvest(){var crypto by remember{mutableStateOf(true)};var amount by remember{mutableStateOf("1000")};var weeks by remember{mutableStateOf("4")};var rate by remember{mutableStateOf("22.5")};val a=amount.toDoubleOrNull()?:0.0;val r=(rate.toDoubleOrNull()?:0.0)/100;val w=weeks.toDoubleOrNull()?:0.0;val end=a*(1+r).pow(w);LazyColumn(contentPadding=PaddingValues(bottom=20.dp)){item{Header("Auto Invest","Choose a strategy and review projected outcomes")};item{Row(Modifier.padding(horizontal=16.dp),horizontalArrangement=Arrangement.spacedBy(8.dp)){Strategy("Cryptocurrency","20–25% / week",Icons.Default.CurrencyBitcoin,crypto){crypto=true};Strategy("Forex","20–25% / week",Icons.Default.CurrencyExchange,!crypto){crypto=false}};Spacer(Modifier.height(13.dp))};item{CardBox(Modifier.padding(horizontal=16.dp)){Column(Modifier.padding(16.dp)){Text(if(crypto)"CRYPTOCURRENCY AUTO INVEST" else "FOREX AUTO INVEST",color=Gold,fontSize=9.sp,fontWeight=FontWeight.Bold);Text("20–25% weekly target range",fontSize=19.sp,fontWeight=FontWeight.Bold);Text("Target/projection only — actual performance may be lower or negative.",color=Muted,fontSize=9.sp);Spacer(Modifier.height(12.dp));Input("Initial amount (USDT)",amount){amount=it};Input("Weeks",weeks){weeks=it};Input("Projection % / week",rate){rate=it};Spacer(Modifier.height(10.dp));Text("Illustrative end value",color=Muted,fontSize=9.sp);Text("%.2f USDT".format(end),color=WhiteGold,fontSize=22.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(10.dp));Button({},Modifier.fillMaxWidth(),colors=ButtonDefaults.buttonColors(Gold)){Text("Review & activate",color=Black,fontSize=11.sp)}}}}}}
@Composable private fun Strategy(t:String,r:String,i:ImageVector,sel:Boolean,go:()->Unit){CardBox(Modifier.width(175.dp).clickable{go()}){Column(Modifier.padding(13.dp)){Icon(i,null,tint=if(sel)Gold else Muted,modifier=Modifier.size(22.dp));Text(t,fontSize=11.sp,fontWeight=FontWeight.Bold);Text(r,color=if(sel)Gold else Muted,fontSize=9.sp);if(sel)Text("SELECTED",color=Gold,fontSize=8.sp,fontWeight=FontWeight.Bold)}}}
@Composable private fun Calculator(){var a by remember{mutableStateOf("1000")};var r by remember{mutableStateOf("22.5")};var w by remember{mutableStateOf("4")};val amount=a.toDoubleOrNull()?:0.0;val rate=(r.toDoubleOrNull()?:0.0)/100;val weeks=w.toDoubleOrNull()?:0.0;val result=amount*(1+rate).pow(weeks);LazyColumn{item{Header("Earnings calculator","Simple projections for everyday users")};item{CardBox(Modifier.padding(16.dp)){Column(Modifier.padding(16.dp)){Input("Starting amount (USDT)",a){a=it};Input("Weekly projection %",r){r=it};Input("Weeks",w){w=it};Spacer(Modifier.height(12.dp));Text("ILLUSTRATIVE END VALUE",color=Muted,fontSize=9.sp);Text("%.2f USDT".format(result),color=WhiteGold,fontSize=25.sp,fontWeight=FontWeight.Bold);Text("Illustrative profit: %.2f USDT".format(result-amount),color=Green,fontSize=10.sp);Text("This calculator does not predict or guarantee investment performance.",color=Muted,fontSize=9.sp,modifier=Modifier.padding(top=8.dp))}}}}}
@Composable private fun Markets(){val list=listOf("BTC / USDT" to "Bitcoin","ETH / USDT" to "Ethereum","SOL / USDT" to "Solana","BNB / USDT" to "BNB");LazyColumn(contentPadding=PaddingValues(bottom=20.dp)){item{Header("Markets","Live market intelligence, movers & analysis")};item{Text("TOP MOVERS",color=Gold,fontSize=9.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(16.dp,4.dp));Row(Modifier.horizontalScroll(rememberScrollState()).padding(horizontal=16.dp),horizontalArrangement=Arrangement.spacedBy(8.dp)){list.take(3).forEach{MarketMini(it.first.substringBefore(" "),"—","Live")}};Spacer(Modifier.height(12.dp))};item{CardBox(Modifier.padding(horizontal=16.dp)){Column(Modifier.padding(15.dp)){Text("MARKET NEWS",color=Gold,fontSize=9.sp,fontWeight=FontWeight.Bold);Text("Latest crypto, forex & macro headlines",fontSize=15.sp,fontWeight=FontWeight.Bold);Text("Dynamic news source will be connected to this native data layer.",color=Muted,fontSize=9.sp)}};Spacer(Modifier.height(12.dp))};items(list){(pair,name)->CardBox(Modifier.padding(5.dp,4.dp).fillMaxWidth()){Row(Modifier.padding(13.dp),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Default.ShowChart,null,tint=Gold,modifier=Modifier.size(22.dp));Spacer(Modifier.width(10.dp));Column(Modifier.weight(1f)){Text(pair,fontSize=11.sp,fontWeight=FontWeight.Bold);Text("$name · live feed",color=Muted,fontSize=9.sp)}Text("—",fontWeight=FontWeight.Bold)}}};item{Row(Modifier.padding(16.dp),horizontalArrangement=Arrangement.spacedBy(8.dp)){CardBox(Modifier.weight(1f)){Column(Modifier.padding(14.dp)){Icon(Icons.Default.AccountBalance,null,tint=Gold);Text("Fundamental",fontWeight=FontWeight.Bold,fontSize=11.sp);Text("Macro, news & metrics",color=Muted,fontSize=9.sp)}};CardBox(Modifier.weight(1f)){Column(Modifier.padding(14.dp)){Icon(Icons.Default.Timeline,null,tint=Gold);Text("Technical",fontWeight=FontWeight.Bold,fontSize=11.sp);Text("Trend, momentum & levels",color=Muted,fontSize=9.sp)}}}}}}
@Composable private fun MarketMini(s:String,p:String,c:String){CardBox(Modifier.width(145.dp)){Column(Modifier.padding(12.dp)){Text(s,color=Gold,fontWeight=FontWeight.Bold,fontSize=10.sp);Text(p,fontSize=15.sp,fontWeight=FontWeight.Bold);Text(c,color=Muted,fontSize=9.sp)}}}
@Composable private fun Profile(theme:()->Unit){LazyColumn{item{Header("Profile","Account, security & preferences")};item{CardBox(Modifier.padding(16.dp)){Column(Modifier.padding(16.dp)){Text("ACCOUNT",color=Gold,fontSize=9.sp,fontWeight=FontWeight.Bold);Text("Not connected",fontWeight=FontWeight.Bold);Text("No balance or transaction data loaded.",color=Muted,fontSize=9.sp);Spacer(Modifier.height(10.dp));Button({},colors=ButtonDefaults.buttonColors(Gold)){Text("Connect",color=Black)}}}};item{CardBox(Modifier.padding(horizontal=16.dp)){Preference("Theme",Icons.Default.DarkMode,"Black-gold / white-gold"){theme()};Preference("Security",Icons.Default.Security,"Account security controls"){};Preference("Notifications",Icons.Default.Notifications,"Market & strategy alerts"){};Preference("Support",Icons.Default.HelpOutline,"Help center") {}}}}}
@Composable private fun Preference(t:String,i:ImageVector,s:String,go:()->Unit){Row(Modifier.fillMaxWidth().clickable{go()}.padding(13.dp),verticalAlignment=Alignment.CenterVertically){Icon(i,null,tint=Gold,modifier=Modifier.size(19.dp));Spacer(Modifier.width(10.dp));Column(Modifier.weight(1f)){Text(t,fontSize=11.sp,fontWeight=FontWeight.Bold);Text(s,color=Muted,fontSize=9.sp)}Icon(Icons.Default.ChevronRight,null,tint=Muted)}}
@Composable private fun Input(label:String,value:String,on:String.()->Unit){OutlinedTextField(value,{on(it)},Modifier.fillMaxWidth().padding(top=8.dp),label={Text(label,fontSize=9.sp)},singleLine=true,textStyle=LocalTextStyle.current.copy(fontSize=11.sp))}
